# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://xenodochial-kare-34379a.netlify.app/*"
  to = "https://achteintel.org/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://fund.achteintel.org/"
  to = "https://wemakeit.com/projects/achteintel-litfassmuseum/"
  status = 301
  force = true

# Redirect newsletter-subdomain
[[redirects]]
  from = "https://newsletter.achteintel.org/"
  to = "https://achteintel.org/newsletter/"
  status = 301
  force = true

# Redirect guide for first exhibition on apple maps
[[redirects]]
  from = "https://achteintel.org/museum/ausstellung-01/karten/apple/"
  to = "https://guides.apple.com/?ug=ChphY2h0ZWludGVs4oCUTGl0ZmFzc011c2V1bRJuGjBMaWViZW5zdGVpbnN0cmHDn2UsIDc2MjI3IEthcmxzcnVoZSwgRGV1dHNjaGxhbmQiEgkUMRaRRYBIQBHj9sgy%2BPQgQComTGl0ZmHDn3PDpHVsZSBBbHRlIFdpbmdhcnRlbmVyIFN0cmHDn2USYxosQW0gU3RhZHRnYXJ0ZW4sIDc2MTM3IEthcmxzcnVoZSwgRGV1dHNjaGxhbmQiEgkEj9QqmH9IQBHfvTSl584gQCofTGl0ZmHDn3PDpHVsZSBFdHRsaW5nZXIgU3RyYcOfZRJwGjhTY2h3YXJ6d2FsZHN0cmHDn2UgMjTigJMyOSwgNzYxMzcgS2FybHNydWhlLCBEZXV0c2NobGFuZCISCRnZXUNRf0hAEXUKOJQbyyBAKiBMaXRmYcOfc8OkdWxlIFNjaHdhcnp3YWxkc3RyYcOfZRJgGixTw7xkZW5kc3RyYcOfZSwgNzYxMzcgS2FybHNydWhlLCBEZXV0c2NobGFuZCISCfXZebzJf0hAEbC2Uo%2FFySBAKhxMaXRmYcOfc8OkdWxlIFPDvGRlbmRzdHJhw59lEoQBGlBab29sb2dpc2NoZXIgU3RhZHRnYXJ0ZW4gS2FybHNydWhlLCBCYWhuaG9mc3RyYcOfZSwgNzYxMzcgS2FybHNydWhlLCBEZXV0c2NobGFuZCISCXbq7ef2f0hAEVhKqcuJyyBAKhxMaXRmYcOfc8OkdWxlIEJhaG5ob2ZzdHJhw59lEmIaL0tyaWVnc3N0cmHDn2UgMTAzLCA3NjEzNSBLYXJsc3J1aGUsIERldXRzY2hsYW5kIhIJDM%2Fy062ASEAR9gHsScnFIEAqG0xpdGZhw59zw6R1bGUgS3JpZWdzc3RyYcOfZRJoGixIb2Zmc3RyYcOfZSAxQiwgNzYxMzMgS2FybHNydWhlLCBEZXV0c2NobGFuZCISCQG2fV2XgUhAEQeF%2Fv9nxiBAKiRMaXRmYcOfc8OkdWxlIFJlaW5ob2xkLUZyYW5rLVN0cmHDn2USYRouTW9sdGtlc3RyYcOfZSAyMCwgNzYxMzMgS2FybHNydWhlLCBEZXV0c2NobGFuZCISCX3jgRjcgUhAEeY1aMAmySBAKhtMaXRmYcOfc8OkdWxlIE1vbHRrZXN0cmHDn2USiAEaU0thcmxzcnVoZXIgSW5zdGl0dXQgZsO8ciBUZWNobm9sb2dpZSwgRW5nbGVyc3RyYcOfZSAyLCA3NjEzMSBLYXJsc3J1aGUsIERldXRzY2hsYW5kIhIJ9uPKDGaBSEAR5TmVgjrRIEAqHUxpdGZhw59zw6R1bGUgV2FsZGhvcm5zdHJhw59lEmkaOE1hcmtncmFmZW5zdHJhw59lIDMwQeKAkzM4LCA3NjEzMyBLYXJsc3J1aGUsIERldXRzY2hsYW5kIhIJSHmjbPCASEAR1%2FSHH0%2FQIEAqGUxpdGZhw59zw6R1bGUgTGlkZWxscGxhdHoSiQEaVkthcmxzcnVoZXIgSW5zdGl0dXQgZsO8ciBUZWNobm9sb2dpZSwgQW0gRmFzYW5lbmdhcnRlbiAzLCA3NjEzMSBLYXJsc3J1aGUsIERldXRzY2hsYW5kIhIJFOZO%2BryBSEARvouSmkPWIEAqG0xpdGZhw59zw6R1bGUgRmFzYW5lbmdhcnRlbhJQGi5Lcm9uZW5zdHJhw59lIDI4LCA3NjEzMyBLYXJsc3J1aGUsIERldXRzY2hsYW5kIhIJl2HlSBaBSEARYZ8F3m7RIEAqCkluZm9zw6R1bGUSZRo1SGFpZC11bmQtTmV1LVN0cmHDn2UgMTQsIDc2MTMxIEthcmxzcnVoZSwgRGV1dHNjaGxhbmQiEgnWSP8KioFIQBGNA6YeydkgQCoYTGl0ZmHDn3PDpHVsZSBPc3RzdGFkdCAx"
  status = 301
  force = true

# Setting security and privacy headers
[[headers]]
  for = "/*"
  [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "no-referrer-when-downgrade"
      Permissions-Policy = "interest-cohort=()"
